# Generated by Django 5.0.6 on 2024-05-18 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_owner_alter_question_pub_date_voter'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='question_picked',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.question'),
            preserve_default=False,
        ),
    ]
