# Generated by Django 5.0.6 on 2024-05-18 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_choice_voter_delete_voter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='voter',
        ),
    ]
