# Generated by Django 5.0.6 on 2024-05-19 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_choice_voter_alter_choice_choice_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='voter',
        ),
    ]
