# Generated by Django 5.0.6 on 2024-05-19 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_vote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
